"""GUI UI string translations for all supported languages.

Extracted from gui/app.py for maintainability.
"""

from __future__ import annotations

_UI_STRINGS: dict[str, dict[str, str]] = {
    "EN": {
        "subtitle": "Mod Translator",
        "label_input": "Input:",
        "label_output": "Output folder:",
        "label_game": "Game:",
        "label_lang": "Language:",
        "label_backend": "Translation engine:",
        "btn_folder": "Folder",
        "btn_file": "File",
        "btn_browse": "Browse",
        "btn_translate": "Translate",
        "btn_cancel": "Cancel",
        "btn_settings": "Settings",
        "btn_restore": "Restore backup",
        "cb_cache": "Remember previous translations",
        "progress_initial": "Select input and click Translate to start",
        "log_label": "Activity log:",
        "ph_input": "Data/ folder or .esp/.esm/.pex file...",
        "ph_output": "(same as input — in-place)",
        "phase_scan": "Scanning",
        "phase_prepare": "Phase 1: Preparing",
        "phase_translate": "Phase 2: Translating",
        "phase_write": "Phase 3: Writing",
        "msg_starting": "Starting...",
        "msg_cancelling": "Cancelling...",
        "msg_error": "Error",
        "backend_hybrid": "Hybrid (Recommended with Nvidia GPU)",
        "backend_opus": "Opus-MT (no GPU)",
        "backend_deepl": "DeepL (needs API key)",
        "tooltip_backend": (
            "Hybrid: Opus-MT + NLLB via CTranslate2 (Nvidia GPU/CUDA).\n"
            "Opus-MT: CTranslate2 model, works well without GPU.\n"
            "DeepL: high-quality online service (needs API key)."
        ),
        "tooltip_cache": (
            "Saves translations to disk to avoid\n"
            "retranslating the same text in future runs.\n"
            "Saves time if you translate the same mods again."
        ),
        "scan_esp": "File: {name} (ESP/ESM)",
        "scan_pex": "File: {name} (PEX)",
        "scan_unsupported": "Unsupported type: {ext}",
        "scan_found": "Found: {parts}",
        "scan_nothing": "No translatable files found",
        "scan_invalid": "Invalid path",
        "scan_plugins": "{n} plugins (ESP/ESM)",
        "scan_scripts": "{n} scripts (PEX)",
        "scan_mcm": "MCM files",
        "completed_files": "Completed - {n} files translated",
        "completed_in": "Completed in {elapsed}",
        "msg_success": "Success",
        "settings_title": "Settings",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Detecting GPU...",
        "settings_models_section": "ML Models",
        "settings_models_checking": "Checking models...",
        "settings_cache_section": "Translation cache",
        "settings_cache_checking": "Checking cache...",
        "settings_cache_clear_btn": "Clear cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Save",
        "settings_gpu_nvidia": "NVIDIA GPU detected: {name} — use Hybrid backend",
        "settings_gpu_none": "No GPU detected (CPU will be used)",
        "settings_model_downloaded": "Downloaded",
        "settings_model_not_downloaded": "Not downloaded",
        "settings_model_download_btn": "Download",
        "settings_model_downloading": "Downloading {name}...",
        "settings_download_ok": "{name} downloaded successfully.",
        "settings_download_err": "Error downloading {name}.",
        "settings_cache_count": "Cached translations: {n}",
        "settings_cache_path": "Location: {path}",
        "settings_cache_cleared": "{n} translations removed from cache.",
        "settings_api_saved": "API key saved.",
    },
    "ES": {
        "subtitle": "Traductor de mods",
        "label_input": "Entrada:",
        "label_output": "Carpeta de salida:",
        "label_game": "Juego:",
        "label_lang": "Idioma:",
        "label_backend": "Motor de traducción:",
        "btn_folder": "Carpeta",
        "btn_file": "Archivo",
        "btn_browse": "Examinar",
        "btn_translate": "Traducir",
        "btn_cancel": "Cancelar",
        "btn_settings": "Ajustes",
        "btn_restore": "Restaurar backup",
        "cb_cache": "Recordar traducciones anteriores",
        "progress_initial": "Selecciona la entrada y pulsa Traducir para empezar",
        "log_label": "Registro de actividad:",
        "ph_input": "Carpeta Data/ o archivo .esp/.esm/.pex...",
        "ph_output": "(misma que la entrada — in-place)",
        "phase_scan": "Escaneando",
        "phase_prepare": "Fase 1: Preparando",
        "phase_translate": "Fase 2: Traduciendo",
        "phase_write": "Fase 3: Escribiendo",
        "msg_starting": "Iniciando...",
        "msg_cancelling": "Cancelando...",
        "msg_error": "Error",
        "backend_hybrid": "Híbrido (Recomendado con GPU Nvidia)",
        "backend_opus": "Opus-MT (sin GPU)",
        "backend_deepl": "DeepL (necesita API key)",
        "tooltip_backend": (
            "Híbrido: Opus-MT + NLLB via CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT: un modelo CTranslate2, funciona bien sin GPU.\n"
            "DeepL: servicio online de alta calidad (necesita API key)."
        ),
        "tooltip_cache": (
            "Guarda las traducciones en disco para no volver\n"
            "a traducir los mismos textos en futuras ejecuciones.\n"
            "Ahorra tiempo si traduces los mismos mods otra vez."
        ),
        "scan_esp": "Archivo: {name} (ESP/ESM)",
        "scan_pex": "Archivo: {name} (PEX)",
        "scan_unsupported": "Tipo no soportado: {ext}",
        "scan_found": "Encontrados: {parts}",
        "scan_nothing": "No se encontraron archivos traducibles",
        "scan_invalid": "Ruta no válida",
        "scan_plugins": "{n} plugins (ESP/ESM)",
        "scan_scripts": "{n} scripts (PEX)",
        "scan_mcm": "archivos MCM",
        "completed_files": "Completado - {n} archivos traducidos",
        "completed_in": "Completado en {elapsed}",
        "msg_success": "Éxito",
        "settings_title": "Ajustes",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Detectando GPU...",
        "settings_models_section": "Modelos ML",
        "settings_models_checking": "Comprobando modelos...",
        "settings_cache_section": "Cache de traducciones",
        "settings_cache_checking": "Comprobando cache...",
        "settings_cache_clear_btn": "Limpiar cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Guardar",
        "settings_gpu_nvidia": "GPU NVIDIA detectada: {name} — usar backend Híbrido",
        "settings_gpu_none": "No se detecta GPU (se usará CPU)",
        "settings_model_downloaded": "Descargado",
        "settings_model_not_downloaded": "No descargado",
        "settings_model_download_btn": "Descargar",
        "settings_model_downloading": "Descargando {name}...",
        "settings_download_ok": "{name} descargado correctamente.",
        "settings_download_err": "Error descargando {name}.",
        "settings_cache_count": "Traducciones en cache: {n}",
        "settings_cache_path": "Ubicación: {path}",
        "settings_cache_cleared": "Se eliminaron {n} traducciones del cache.",
        "settings_api_saved": "API key guardada.",
    },
    "FR": {
        "subtitle": "Traducteur de mods",
        "label_input": "Entrée :",
        "label_output": "Dossier de sortie :",
        "label_game": "Jeu :",
        "label_lang": "Langue :",
        "label_backend": "Moteur de traduction :",
        "btn_folder": "Dossier",
        "btn_file": "Fichier",
        "btn_browse": "Parcourir",
        "btn_translate": "Traduire",
        "btn_cancel": "Annuler",
        "btn_settings": "Paramètres",
        "btn_restore": "Restaurer sauvegarde",
        "cb_cache": "Mémoriser les traductions précédentes",
        "progress_initial": "Sélectionne l'entrée et clique sur Traduire pour commencer",
        "log_label": "Journal d'activité :",
        "ph_input": "Dossier Data/ ou fichier .esp/.esm/.pex...",
        "ph_output": "(même que l'entrée — en place)",
        "phase_scan": "Analyse en cours",
        "phase_prepare": "Phase 1 : Préparation",
        "phase_translate": "Phase 2 : Traduction",
        "phase_write": "Phase 3 : Écriture",
        "msg_starting": "Démarrage...",
        "msg_cancelling": "Annulation...",
        "msg_error": "Erreur",
        "backend_hybrid": "Hybride (Recommandé avec GPU Nvidia)",
        "backend_opus": "Opus-MT (sans GPU)",
        "backend_deepl": "DeepL (nécessite une clé API)",
        "tooltip_backend": (
            "Hybride : Opus-MT + NLLB via CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT : modèle CTranslate2, fonctionne sans GPU.\n"
            "DeepL : service en ligne haute qualité (clé API requise)."
        ),
        "tooltip_cache": (
            "Enregistre les traductions sur disque pour ne pas\n"
            "retraduire les mêmes textes lors des prochaines exécutions.\n"
            "Gain de temps si vous traduisez les mêmes mods à nouveau."
        ),
        "scan_esp": "Fichier : {name} (ESP/ESM)",
        "scan_pex": "Fichier : {name} (PEX)",
        "scan_unsupported": "Type non supporté : {ext}",
        "scan_found": "Trouvé : {parts}",
        "scan_nothing": "Aucun fichier traduisible trouvé",
        "scan_invalid": "Chemin invalide",
        "scan_plugins": "{n} plugins (ESP/ESM)",
        "scan_scripts": "{n} scripts (PEX)",
        "scan_mcm": "fichiers MCM",
        "completed_files": "Terminé - {n} fichiers traduits",
        "completed_in": "Terminé en {elapsed}",
        "msg_success": "Succès",
        "settings_title": "Paramètres",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Détection du GPU...",
        "settings_models_section": "Modèles ML",
        "settings_models_checking": "Vérification des modèles...",
        "settings_cache_section": "Cache de traductions",
        "settings_cache_checking": "Vérification du cache...",
        "settings_cache_clear_btn": "Vider le cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Enregistrer",
        "settings_gpu_nvidia": "GPU NVIDIA détecté : {name} — utiliser le backend Hybride",
        "settings_gpu_none": "Pas de GPU détecté (utilisation du CPU)",
        "settings_model_downloaded": "Téléchargé",
        "settings_model_not_downloaded": "Non téléchargé",
        "settings_model_download_btn": "Télécharger",
        "settings_model_downloading": "Téléchargement de {name}...",
        "settings_download_ok": "{name} téléchargé avec succès.",
        "settings_download_err": "Erreur lors du téléchargement de {name}.",
        "settings_cache_count": "Traductions en cache : {n}",
        "settings_cache_path": "Emplacement : {path}",
        "settings_cache_cleared": "{n} traductions supprimées du cache.",
        "settings_api_saved": "Clé API enregistrée.",
    },
    "DE": {
        "subtitle": "Mod-Übersetzer",
        "label_input": "Eingabe:",
        "label_output": "Ausgabeordner:",
        "label_game": "Spiel:",
        "label_lang": "Sprache:",
        "label_backend": "Übersetzungsmotor:",
        "btn_folder": "Ordner",
        "btn_file": "Datei",
        "btn_browse": "Durchsuchen",
        "btn_translate": "Übersetzen",
        "btn_cancel": "Abbrechen",
        "btn_settings": "Einstellungen",
        "btn_restore": "Backup wiederherstellen",
        "cb_cache": "Frühere Übersetzungen speichern",
        "progress_initial": "Eingabe auswählen und auf Übersetzen klicken",
        "log_label": "Aktivitätsprotokoll:",
        "ph_input": "Data/-Ordner oder .esp/.esm/.pex-Datei...",
        "ph_output": "(gleicher Ordner wie Eingabe — in-place)",
        "phase_scan": "Scannen",
        "phase_prepare": "Phase 1: Vorbereitung",
        "phase_translate": "Phase 2: Übersetzung",
        "phase_write": "Phase 3: Schreiben",
        "msg_starting": "Starten...",
        "msg_cancelling": "Abbrechen...",
        "msg_error": "Fehler",
        "backend_hybrid": "Hybrid (Empfohlen mit Nvidia GPU)",
        "backend_opus": "Opus-MT (ohne GPU)",
        "backend_deepl": "DeepL (braucht API-Schlüssel)",
        "tooltip_backend": (
            "Hybrid: Opus-MT + NLLB via CTranslate2 (Nvidia GPU/CUDA).\n"
            "Opus-MT: CTranslate2-Modell, funktioniert ohne GPU.\n"
            "DeepL: Online-Dienst hoher Qualität (API-Schlüssel erforderlich)."
        ),
        "tooltip_cache": (
            "Speichert Übersetzungen auf Disk, damit dieselben Texte\n"
            "bei zukünftigen Ausführungen nicht erneut übersetzt werden.\n"
            "Spart Zeit beim erneuten Übersetzen derselben Mods."
        ),
        "scan_esp": "Datei: {name} (ESP/ESM)",
        "scan_pex": "Datei: {name} (PEX)",
        "scan_unsupported": "Nicht unterstützter Typ: {ext}",
        "scan_found": "Gefunden: {parts}",
        "scan_nothing": "Keine übersetzbaren Dateien gefunden",
        "scan_invalid": "Ungültiger Pfad",
        "scan_plugins": "{n} Plugins (ESP/ESM)",
        "scan_scripts": "{n} Skripte (PEX)",
        "scan_mcm": "MCM-Dateien",
        "completed_files": "Abgeschlossen - {n} Dateien übersetzt",
        "completed_in": "Abgeschlossen in {elapsed}",
        "msg_success": "Erfolg",
        "settings_title": "Einstellungen",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "GPU wird erkannt...",
        "settings_models_section": "ML-Modelle",
        "settings_models_checking": "Modelle werden geprüft...",
        "settings_cache_section": "Übersetzungs-Cache",
        "settings_cache_checking": "Cache wird geprüft...",
        "settings_cache_clear_btn": "Cache leeren",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Speichern",
        "settings_gpu_nvidia": "NVIDIA-GPU erkannt: {name} — Hybrid-Backend verwenden",
        "settings_gpu_none": "Keine GPU erkannt (CPU wird verwendet)",
        "settings_model_downloaded": "Heruntergeladen",
        "settings_model_not_downloaded": "Nicht heruntergeladen",
        "settings_model_download_btn": "Herunterladen",
        "settings_model_downloading": "{name} wird heruntergeladen...",
        "settings_download_ok": "{name} erfolgreich heruntergeladen.",
        "settings_download_err": "Fehler beim Herunterladen von {name}.",
        "settings_cache_count": "Gecachte Übersetzungen: {n}",
        "settings_cache_path": "Speicherort: {path}",
        "settings_cache_cleared": "{n} Übersetzungen aus dem Cache gelöscht.",
        "settings_api_saved": "API-Schlüssel gespeichert.",
    },
    "IT": {
        "subtitle": "Traduttore di mod",
        "label_input": "Ingresso:",
        "label_output": "Cartella di uscita:",
        "label_game": "Gioco:",
        "label_lang": "Lingua:",
        "label_backend": "Motore di traduzione:",
        "btn_folder": "Cartella",
        "btn_file": "File",
        "btn_browse": "Sfoglia",
        "btn_translate": "Traduci",
        "btn_cancel": "Annulla",
        "btn_settings": "Impostazioni",
        "btn_restore": "Ripristina backup",
        "cb_cache": "Ricorda le traduzioni precedenti",
        "progress_initial": "Seleziona l'ingresso e clicca Traduci per iniziare",
        "log_label": "Registro attività:",
        "ph_input": "Cartella Data/ o file .esp/.esm/.pex...",
        "ph_output": "(stessa dell'ingresso — in-place)",
        "phase_scan": "Scansione",
        "phase_prepare": "Fase 1: Preparazione",
        "phase_translate": "Fase 2: Traduzione",
        "phase_write": "Fase 3: Scrittura",
        "msg_starting": "Avvio...",
        "msg_cancelling": "Annullamento...",
        "msg_error": "Errore",
        "backend_hybrid": "Ibrido (Consigliato con GPU Nvidia)",
        "backend_opus": "Opus-MT (senza GPU)",
        "backend_deepl": "DeepL (richiede chiave API)",
        "tooltip_backend": (
            "Ibrido: Opus-MT + NLLB via CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT: modello CTranslate2, funziona senza GPU.\n"
            "DeepL: servizio online di alta qualità (richiede chiave API)."
        ),
        "tooltip_cache": (
            "Salva le traduzioni su disco per non ritradurre\n"
            "gli stessi testi nelle future esecuzioni.\n"
            "Risparmia tempo se traduci gli stessi mod di nuovo."
        ),
        "scan_esp": "File: {name} (ESP/ESM)",
        "scan_pex": "File: {name} (PEX)",
        "scan_unsupported": "Tipo non supportato: {ext}",
        "scan_found": "Trovati: {parts}",
        "scan_nothing": "Nessun file traducibile trovato",
        "scan_invalid": "Percorso non valido",
        "scan_plugins": "{n} plugin (ESP/ESM)",
        "scan_scripts": "{n} script (PEX)",
        "scan_mcm": "file MCM",
        "completed_files": "Completato - {n} file tradotti",
        "completed_in": "Completato in {elapsed}",
        "msg_success": "Successo",
        "settings_title": "Impostazioni",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Rilevamento GPU...",
        "settings_models_section": "Modelli ML",
        "settings_models_checking": "Controllo modelli...",
        "settings_cache_section": "Cache traduzioni",
        "settings_cache_checking": "Controllo cache...",
        "settings_cache_clear_btn": "Svuota cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Salva",
        "settings_gpu_nvidia": "GPU NVIDIA rilevata: {name} — usare il backend Ibrido",
        "settings_gpu_none": "Nessuna GPU rilevata (verrà usata la CPU)",
        "settings_model_downloaded": "Scaricato",
        "settings_model_not_downloaded": "Non scaricato",
        "settings_model_download_btn": "Scarica",
        "settings_model_downloading": "Download di {name}...",
        "settings_download_ok": "{name} scaricato correttamente.",
        "settings_download_err": "Errore nel download di {name}.",
        "settings_cache_count": "Traduzioni in cache: {n}",
        "settings_cache_path": "Posizione: {path}",
        "settings_cache_cleared": "{n} traduzioni rimosse dalla cache.",
        "settings_api_saved": "Chiave API salvata.",
    },
    "PT": {
        "subtitle": "Tradutor de mods",
        "label_input": "Entrada:",
        "label_output": "Pasta de saída:",
        "label_game": "Jogo:",
        "label_lang": "Idioma:",
        "label_backend": "Motor de tradução:",
        "btn_folder": "Pasta",
        "btn_file": "Arquivo",
        "btn_browse": "Procurar",
        "btn_translate": "Traduzir",
        "btn_cancel": "Cancelar",
        "btn_settings": "Configurações",
        "btn_restore": "Restaurar backup",
        "cb_cache": "Lembrar traduções anteriores",
        "progress_initial": "Selecione a entrada e clique em Traduzir para começar",
        "log_label": "Registro de atividade:",
        "ph_input": "Pasta Data/ ou arquivo .esp/.esm/.pex...",
        "ph_output": "(mesma que a entrada — in-place)",
        "phase_scan": "Varrendo",
        "phase_prepare": "Fase 1: Preparando",
        "phase_translate": "Fase 2: Traduzindo",
        "phase_write": "Fase 3: Escrevendo",
        "msg_starting": "Iniciando...",
        "msg_cancelling": "Cancelando...",
        "msg_error": "Erro",
        "backend_hybrid": "Híbrido (Recomendado com GPU Nvidia)",
        "backend_opus": "Opus-MT (sem GPU)",
        "backend_deepl": "DeepL (precisa de chave API)",
        "tooltip_backend": (
            "Híbrido: Opus-MT + NLLB via CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT: modelo CTranslate2, funciona sem GPU.\n"
            "DeepL: serviço online de alta qualidade (requer chave API)."
        ),
        "tooltip_cache": (
            "Salva traduções em disco para não traduzir\n"
            "os mesmos textos em execuções futuras.\n"
            "Economiza tempo ao traduzir os mesmos mods novamente."
        ),
        "scan_esp": "Arquivo: {name} (ESP/ESM)",
        "scan_pex": "Arquivo: {name} (PEX)",
        "scan_unsupported": "Tipo não suportado: {ext}",
        "scan_found": "Encontrados: {parts}",
        "scan_nothing": "Nenhum arquivo traduzível encontrado",
        "scan_invalid": "Caminho inválido",
        "scan_plugins": "{n} plugins (ESP/ESM)",
        "scan_scripts": "{n} scripts (PEX)",
        "scan_mcm": "arquivos MCM",
        "completed_files": "Concluído - {n} arquivos traduzidos",
        "completed_in": "Concluído em {elapsed}",
        "msg_success": "Êxito",
        "settings_title": "Configurações",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Detectando GPU...",
        "settings_models_section": "Modelos ML",
        "settings_models_checking": "Verificando modelos...",
        "settings_cache_section": "Cache de traduções",
        "settings_cache_checking": "Verificando cache...",
        "settings_cache_clear_btn": "Limpar cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Salvar",
        "settings_gpu_nvidia": "GPU NVIDIA detectada: {name} — usar backend Híbrido",
        "settings_gpu_none": "Nenhuma GPU detectada (será usada a CPU)",
        "settings_model_downloaded": "Baixado",
        "settings_model_not_downloaded": "Não baixado",
        "settings_model_download_btn": "Baixar",
        "settings_model_downloading": "Baixando {name}...",
        "settings_download_ok": "{name} baixado com sucesso.",
        "settings_download_err": "Erro ao baixar {name}.",
        "settings_cache_count": "Traduções em cache: {n}",
        "settings_cache_path": "Localização: {path}",
        "settings_cache_cleared": "{n} traduções removidas do cache.",
        "settings_api_saved": "Chave API salva.",
    },
    "RU": {
        "subtitle": "Переводчик модов",
        "label_input": "Вход:",
        "label_output": "Папка вывода:",
        "label_game": "Игра:",
        "label_lang": "Язык:",
        "label_backend": "Движок перевода:",
        "btn_folder": "Папка",
        "btn_file": "Файл",
        "btn_browse": "Обзор",
        "btn_translate": "Перевести",
        "btn_cancel": "Отмена",
        "btn_settings": "Настройки",
        "btn_restore": "Восстановить копию",
        "cb_cache": "Запомнить переводы",
        "progress_initial": "Выберите источник и нажмите Перевести",
        "log_label": "Журнал активности:",
        "ph_input": "Папка Data/ или файл .esp/.esm/.pex...",
        "ph_output": "(та же, что и вход)",
        "phase_scan": "Сканирование",
        "phase_prepare": "Фаза 1: Подготовка",
        "phase_translate": "Фаза 2: Перевод",
        "phase_write": "Фаза 3: Запись",
        "msg_starting": "Запуск...",
        "msg_cancelling": "Отмена...",
        "msg_error": "Ошибка",
        "backend_hybrid": "Гибрид (рек. с GPU Nvidia)",
        "backend_opus": "Opus-MT (без GPU)",
        "backend_deepl": "DeepL (нужен API ключ)",
        "tooltip_backend": (
            "Гибрид: Opus-MT + NLLB через CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT: модель CTranslate2, работает без GPU.\n"
            "DeepL: онлайн-сервис высокого качества (нужен API ключ)."
        ),
        "tooltip_cache": (
            "Сохраняет переводы на диске, чтобы не переводить\n"
            "те же тексты при следующих запусках.\n"
            "Экономит время при повторном переводе тех же модов."
        ),
        "scan_esp": "Файл: {name} (ESP/ESM)",
        "scan_pex": "Файл: {name} (PEX)",
        "scan_unsupported": "Тип не поддерживается: {ext}",
        "scan_found": "Найдено: {parts}",
        "scan_nothing": "Переводимые файлы не найдены",
        "scan_invalid": "Неверный путь",
        "scan_plugins": "{n} плагинов (ESP/ESM)",
        "scan_scripts": "{n} скриптов (PEX)",
        "scan_mcm": "файлы MCM",
        "completed_files": "Завершено — {n} файлов переведено",
        "completed_in": "Завершено за {elapsed}",
        "msg_success": "Успех",
        "settings_title": "Настройки",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Определение GPU...",
        "settings_models_section": "Модели ML",
        "settings_models_checking": "Проверка моделей...",
        "settings_cache_section": "Кэш переводов",
        "settings_cache_checking": "Проверка кэша...",
        "settings_cache_clear_btn": "Очистить кэш",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Сохранить",
        "settings_gpu_nvidia": "Обнаружена GPU NVIDIA: {name} — использовать гибридный бэкенд",
        "settings_gpu_none": "GPU не обнаружена (будет использоваться CPU)",
        "settings_model_downloaded": "Загружено",
        "settings_model_not_downloaded": "Не загружено",
        "settings_model_download_btn": "Загрузить",
        "settings_model_downloading": "Загрузка {name}...",
        "settings_download_ok": "{name} успешно загружено.",
        "settings_download_err": "Ошибка загрузки {name}.",
        "settings_cache_count": "Переводов в кэше: {n}",
        "settings_cache_path": "Расположение: {path}",
        "settings_cache_cleared": "{n} переводов удалено из кэша.",
        "settings_api_saved": "API-ключ сохранён.",
    },
    "PL": {
        "subtitle": "Tłumacz modów",
        "label_input": "Wejście:",
        "label_output": "Folder wyjściowy:",
        "label_game": "Gra:",
        "label_lang": "Język:",
        "label_backend": "Silnik tłumaczenia:",
        "btn_folder": "Folder",
        "btn_file": "Plik",
        "btn_browse": "Przeglądaj",
        "btn_translate": "Tłumacz",
        "btn_cancel": "Anuluj",
        "btn_settings": "Ustawienia",
        "btn_restore": "Przywróć kopię",
        "cb_cache": "Pamiętaj tłumaczenia",
        "progress_initial": "Wybierz wejście i kliknij Tłumacz, aby rozpocząć",
        "log_label": "Dziennik aktywności:",
        "ph_input": "Folder Data/ lub plik .esp/.esm/.pex...",
        "ph_output": "(ten sam co wejście — w miejscu)",
        "phase_scan": "Skanowanie",
        "phase_prepare": "Faza 1: Przygotowanie",
        "phase_translate": "Faza 2: Tłumaczenie",
        "phase_write": "Faza 3: Zapis",
        "msg_starting": "Uruchamianie...",
        "msg_cancelling": "Anulowanie...",
        "msg_error": "Błąd",
        "backend_hybrid": "Hybrydowy (z GPU Nvidia)",
        "backend_opus": "Opus-MT (bez GPU)",
        "backend_deepl": "DeepL (wymaga klucza API)",
        "tooltip_backend": (
            "Hybrydowy: Opus-MT + NLLB przez CTranslate2 (GPU Nvidia/CUDA).\n"
            "Opus-MT: model CTranslate2, działa bez GPU.\n"
            "DeepL: usługa online wysokiej jakości (wymagany klucz API)."
        ),
        "tooltip_cache": (
            "Zapisuje tłumaczenia na dysk, aby nie tłumaczyć\n"
            "tych samych tekstów w przyszłych uruchomieniach.\n"
            "Oszczędza czas przy ponownym tłumaczeniu tych samych modów."
        ),
        "scan_esp": "Plik: {name} (ESP/ESM)",
        "scan_pex": "Plik: {name} (PEX)",
        "scan_unsupported": "Nieobsługiwany typ: {ext}",
        "scan_found": "Znaleziono: {parts}",
        "scan_nothing": "Nie znaleziono plików do tłumaczenia",
        "scan_invalid": "Nieprawidłowa ścieżka",
        "scan_plugins": "{n} pluginów (ESP/ESM)",
        "scan_scripts": "{n} skryptów (PEX)",
        "scan_mcm": "pliki MCM",
        "completed_files": "Ukończono — {n} pliki przetłumaczone",
        "completed_in": "Ukończono w {elapsed}",
        "msg_success": "Sukces",
        "settings_title": "Ustawienia",
        "settings_gpu_section": "GPU / CUDA",
        "settings_gpu_detecting": "Wykrywanie GPU...",
        "settings_models_section": "Modele ML",
        "settings_models_checking": "Sprawdzanie modeli...",
        "settings_cache_section": "Pamięć podręczna",
        "settings_cache_checking": "Sprawdzanie cache...",
        "settings_cache_clear_btn": "Wyczyść cache",
        "settings_deepl_section": "DeepL API Key",
        "settings_save_btn": "Zapisz",
        "settings_gpu_nvidia": "Wykryto GPU NVIDIA: {name} — użyj backendu hybrydowego",
        "settings_gpu_none": "Nie wykryto GPU (zostanie użyty CPU)",
        "settings_model_downloaded": "Pobrano",
        "settings_model_not_downloaded": "Nie pobrano",
        "settings_model_download_btn": "Pobierz",
        "settings_model_downloading": "Pobieranie {name}...",
        "settings_download_ok": "{name} pobrano pomyślnie.",
        "settings_download_err": "Błąd pobierania {name}.",
        "settings_cache_count": "Tłumaczenia w cache: {n}",
        "settings_cache_path": "Lokalizacja: {path}",
        "settings_cache_cleared": "{n} tłumaczeń usuniętych z cache.",
        "settings_api_saved": "Klucz API zapisany.",
    },
}
